name: Test
on: [push, pull_request]

jobs:
  test_cli:
    runs-on: ubuntu-latest
    name: Test CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt --use-feature=2020-resolver
      - name: Install external dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m spacy download en_core_web_sm
      - name: Run example query
        run: python frank_cli.py -q 'What is the population of Finland in 2019?'
